version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    volumes:
      - 'pg:/var/lib/postgresql/data'
  api:
    container_name: xrt-api
    image: retrotool/api:latest
    command: start
    env_file: api.env
    restart: always
    links:
      - postgres
    depends_on:
      - postgres
  client:
    container_name: xrt-client
    image: retrotool/client:latest
    restart: always
    links:
      - api
    depends_on:
      - api
  proxy:
    container_name: xrt-proxy
    image: retrotool/proxy:latest
    restart: always
    ports:
      - 3000:80
    links:
      - client
      - api
    depends_on:
      - client
      - api

volumes:
  pg:
