version: '3'
services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - 'pg:/var/lib/postgresql/data'
  api:
    image: retrotool/api:latest
    env_file: api.env
    links:
      - postgres
    depends_on:
      - postgres
  client:
    image: retrotool/client:latest
    links:
      - api
    depends_on:
      - api
  proxy:
    image: retrotool/proxy:latest
    ports:
      - 3000:80
    links:
      - client
      - api
    depends_on:
      - client
      - api

volumes:
  pg:
